[package]
name = "mlatu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { version = "0.27", features = ["derive"] }
thiserror = "2"
rand = "0.9"
